#!/bin/bash

set -e

CATALINA_HOME=/usr/share/tomcat7-codedeploy

# Tar file name
TOMCAT7_CORE_TAR_FILENAME='apache-tomcat-7.0.73.tar.gz'
# Download URL for Tomcat7 core
TOMCAT7_CORE_DOWNLOAD_URL="http://mirror.olnevhost.net/pub/apache/tomcat/tomcat-7/v7.0.73/bin/$TOMCAT7_CORE_TAR_FILENAME"
# The top-level directory after unpacking the tar file
TOMCAT7_CORE_UNPACKED_DIRNAME='apache-tomcat-7.0.73'


# Check whether there exists a valid instance
# of Tomcat7 installed at the specified directory
[[ -d $CATALINA_HOME ]] && { /sbin/service tomcat7 status; } && {
    /bin/echo "Tomcat7 is already installed at $CATALINA_HOME. Skip reinstalling it."
    exit 0
}

# Clear install directory
if [ -d $CATALINA_HOME ]; then
    /bin/rm -rf $CATALINA_HOME
fi
/bin/mkdir -p $CATALINA_HOME

# Download the latest Tomcat7 version
cd /tmp
{ /usr/bin/which wget; } || { /usr/bin/yum install wget; }
/usr/bin/wget $TOMCAT7_CORE_DOWNLOAD_URL
if [[ -d /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME ]]; then
    /usr/rm -rf /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME
fi
/bin/tar xzf $TOMCAT7_CORE_TAR_FILENAME

# Copy over to the CATALINA_HOME
/bin/cp -r /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME/* $CATALINA_HOME

# Install Java if not yet installed
{ /usr/bin/which java; } || { /usr/bin/yum install java; }

# Create the service init.d script
/bin/cat > /etc/init.d/tomcat7 <<'EOF'
#!/bin/bash
# description: Tomcat7 Start Stop Restart
# processname: tomcat7
PATH=$JAVA_HOME/bin:$PATH
export PATH
CATALINA_HOME='/usr/share/tomcat7-codedeploy'

case $1 in
start)
/bin/sh $CATALINA_HOME/bin/startup.sh
;;
stop)
/bin/sh $CATALINA_HOME/bin/shutdown.sh
;;
restart)
/bin/sh $CATALINA_HOME/bin/shutdown.sh
/bin/sh $CATALINA_HOME/bin/startup.sh
;;
esac
exit 0
EOF

# Change permission mode for the service script
/bin/chmod 755 /etc/init.d/tomcat7

